### ISSUE TITLE
trouble substituting values from data frame into raster

### ISSUE THREAD

**Issue by bbest** [resilienseas/resilienseas.github.io#2]
from @raetaylorburns...

Hi @bbest!
Thanks for all your GitHub help yesterday! We rasterized the monitoring inventory polygons and set up the framework for calculating variability, but we ran into an issue when trying to assign a monitoring site measurement to the rasterized polygons in this step https://github.com/resilienseas/resilienseas.github.io/blob/fe5248f441eb437eacd568bc5138a342a541d7df/scripts/gapanalysis.R#L155-L156. We think it is because the length of the SST dataframe is different from the number of values in the raster. Any ideas on how to address this issue?
Thanks!

**Comment by bbest** [comment]
Hi @raetaylorburns,

Please also include the error message you get when you submit an issue ;) Here's what I get when I run https://github.com/resilienseas/resilienseas.github.io/blob/fe5248f441eb437eacd568bc5138a342a541d7df/scripts/gapanalysis.R#L156
```
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘subs’ for signature ‘"numeric", "data.frame"’
```

Per the [Rdocumentation on `substitute()`](https://www.rdocumentation.org/packages/raster/versions/2.6-7/topics/substitute), please check your argument inputs.

  `subs(x, y, by=1, which=2, subsWithNA=TRUE, filename='', ...)`
  
  - `x` should be a raster object, not the data frame contained by a raster
  -  `by` should be a column number or name, as in character string
  - `which`, same as `by`

So, this seems to work:

```r
polygonsst <- subs(vorraster, sitesst, by="id", which="SST")
plot(polygonsst, col=my.colors(1000))
```

![image](https://user-images.githubusercontent.com/2837257/35476340-25c1b8ec-0363-11e8-813d-bb4171586a8d.png)

Going to close this issue with the message "fixed raster::subs issue. closes #2" in my Git commit, then push to get it onto Github and automatically close the issue, per [Closing issues using keywords - User Documentation](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by raetaylorburns** [comment]
Hi @bbest,
Thanks so much - we'll will provide error message in any issues going forward. We did a preliminary version of the gap analysis per the method we talked about yesterday - success!

**Comment by bbest** [comment]
Yay, glad to hear 🎉
